# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'Speak in' do
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    # Pods for Speak in
    pod 'Alamofire', '~> 4.0'
    pod 'Charts'
    pod 'Charts/Realm'
    pod 'RealmSwift'
    pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end



